# 프로그래머스 MYSQL LEVEL3. 오랜 기간 보호한 동물(1)
# 주소: https://programmers.co.kr/learn/courses/30/lessons/59044

SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME ASC
LIMIT 3
