# 프로그래머스 MYSQL LEVEL3. 없어진 기록 찾기
# 주소: https://programmers.co.kr/learn/courses/30/lessons/59042

SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
LEFT JOIN ANIMAL_INS
    ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL